/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teste;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Maria Lucia
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadastrarGenero = new javax.swing.JMenuItem();
        cadastrarArtista = new javax.swing.JMenuItem();
        cadastrarAlbum = new javax.swing.JMenuItem();
        cadastrarMusica = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        pesquisaMusica = new javax.swing.JMenuItem();
        pesquisaArtista = new javax.swing.JMenuItem();
        pesquisaAlbum = new javax.swing.JMenuItem();
        relatorioCompleto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Músicas");

        jDesktopPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/headphones-clip-art-stylephones2_1.png"))); // NOI18N

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(226, 226, 226))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        jMenu1.setText("Cadastro");

        cadastrarGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cd_add.png"))); // NOI18N
        cadastrarGenero.setText("Cadastrar Gênero");
        cadastrarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarGeneroActionPerformed(evt);
            }
        });
        jMenu1.add(cadastrarGenero);

        cadastrarArtista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user_add.png"))); // NOI18N
        cadastrarArtista.setText("Cadastrar Artista");
        cadastrarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarArtistaActionPerformed(evt);
            }
        });
        jMenu1.add(cadastrarArtista);

        cadastrarAlbum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/book_add.png"))); // NOI18N
        cadastrarAlbum.setText("Cadastrar Álbum");
        cadastrarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAlbumActionPerformed(evt);
            }
        });
        jMenu1.add(cadastrarAlbum);

        cadastrarMusica.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/music.png"))); // NOI18N
        cadastrarMusica.setText("Cadastrar Música");
        cadastrarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarMusicaActionPerformed(evt);
            }
        });
        jMenu1.add(cadastrarMusica);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/zoom.png"))); // NOI18N
        jMenu2.setText("Pesquisar");

        pesquisaMusica.setText("Música");
        pesquisaMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaMusicaActionPerformed(evt);
            }
        });
        jMenu2.add(pesquisaMusica);

        pesquisaArtista.setText("Artista");
        pesquisaArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaArtistaActionPerformed(evt);
            }
        });
        jMenu2.add(pesquisaArtista);

        pesquisaAlbum.setText("Álbum");
        pesquisaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaAlbumActionPerformed(evt);
            }
        });
        jMenu2.add(pesquisaAlbum);

        relatorioCompleto.setText("Relatório completo");
        relatorioCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioCompletoActionPerformed(evt);
            }
        });
        jMenu2.add(relatorioCompleto);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarGeneroActionPerformed
        TelaCadastroGenero tcg = new TelaCadastroGenero();
        jDesktopPane1.add(tcg);
        tcg.setVisible(true);
        
    }//GEN-LAST:event_cadastrarGeneroActionPerformed

    private void cadastrarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAlbumActionPerformed
        TelaCadastroAlbum tcal = new TelaCadastroAlbum();
        jDesktopPane1.add(tcal);
        tcal.setVisible(true);
    }//GEN-LAST:event_cadastrarAlbumActionPerformed

    private void cadastrarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarArtistaActionPerformed
        TelaCadastroArtista tcar= new TelaCadastroArtista();
        jDesktopPane1.add(tcar);
        tcar.setVisible(true);
                
    }//GEN-LAST:event_cadastrarArtistaActionPerformed

    private void cadastrarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarMusicaActionPerformed
       TelaCadastroMusica tcmu = new TelaCadastroMusica();
       jDesktopPane1.add(tcmu);
       tcmu.setVisible(true);
    }//GEN-LAST:event_cadastrarMusicaActionPerformed

    private void pesquisaMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaMusicaActionPerformed
        PesquisaMusica pmu = new PesquisaMusica();
        jDesktopPane1.add(pmu);
        pmu.setVisible(true);
    }//GEN-LAST:event_pesquisaMusicaActionPerformed

    private void pesquisaArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaArtistaActionPerformed
        PesquisaArtista par = new PesquisaArtista();
        jDesktopPane1.add(par);
        par.setVisible(true);
    }//GEN-LAST:event_pesquisaArtistaActionPerformed

    private void pesquisaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaAlbumActionPerformed
        PesquisaAlbum pal = new PesquisaAlbum();
        jDesktopPane1.add(pal);
        pal.setVisible(true);
    }//GEN-LAST:event_pesquisaAlbumActionPerformed

    private void relatorioCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioCompletoActionPerformed
        RelatorioCompleto rco = new RelatorioCompleto();
        jDesktopPane1.add(rco);
        rco.setVisible(true);
    }//GEN-LAST:event_relatorioCompletoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarAlbum;
    private javax.swing.JMenuItem cadastrarArtista;
    private javax.swing.JMenuItem cadastrarGenero;
    private javax.swing.JMenuItem cadastrarMusica;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem pesquisaAlbum;
    private javax.swing.JMenuItem pesquisaArtista;
    private javax.swing.JMenuItem pesquisaMusica;
    private javax.swing.JMenuItem relatorioCompleto;
    // End of variables declaration//GEN-END:variables
}
